ember-codemods/ember-angle-brackets-codemod

- transforms/angle-brackets/__testFixtures__/deeply-nested-sub.input.hbs
- transforms/angle-brackets/__testFixtures__/deeply-nested-sub.output.hbs
- transforms/angle-brackets/transforms/angle-brackets-syntax.js
fixes #9.  Use recursion until no more subexpressions
> fix deeply nested sub expressions

- transforms/angle-brackets/__testfixtures__/data-attributes.input.hbs
- transforms/angle-brackets/__testfixtures__/data-attributes.output.hbs
- transforms/angle-brackets/transforms/angle-brackets-syntax.js
closes https://github.com/rajasegar/ember-angle-brackets-codemod/issues/15
> add support for `data-*` attributes

- transforms/angle-brackets/__testfixtures__/deeply-nested-sub.input.hbs
- transforms/angle-brackets/__testfixtures__/deeply-nested-sub.output.hbs
- transforms/angle-brackets/transforms/angle-brackets-syntax.js
closes https://github.com/rajasegar/ember-angle-brackets-codemod/issues/24
> allow helpers with positional and named args

- transforms/angle-brackets/__testfixtures__/link-to-inline.input.hbs
- transforms/angle-brackets/__testfixtures__/link-to-inline.output.hbs
- transforms/angle-brackets/transforms/angle-brackets-syntax.js
fixes https://github.com/rajasegar/ember-angle-brackets-codemod/issues/31
> Support inline link-to

- transforms/angle-brackets/__testfixtures__/tag-name.input.hbs
- transforms/angle-brackets/__testfixtures__/tag-name.output.hbs
failing test for https://github.com/rajasegar/ember-angle-brackets-codemod/issues/33
> failing test for `tagName=""

- transforms/angle-brackets/__testfixtures__/data-attributes.input.hbs
- transforms/angle-brackets/__testfixtures__/data-attributes.output.hbs
- transforms/angle-brackets/__testfixtures__/sample.input.hbs
- transforms/angle-brackets/__testfixtures__/sample.output.hbs
- transforms/angle-brackets/transforms/angle-brackets-syntax.js
fixes #33 & #38, also allows for valueless data-*
> Workaround for empty string => tagName=""

- transforms/angle-brackets/__testfixtures__/actions.output.hbs
- transforms/angle-brackets/transforms/angle-brackets-syntax.js
based on @tylerturdenpants's PR https://github.com/rajasegar/ember-angle-brackets-codemod/pull/39
> better support number literals

- README.md
Slyly stolen from https://github.com/lifeart/ember-ast-hot-load
Thanks @lifeart :)
> Add command to get App Helpers

- package-lock.json
- package.json
- transforms/angle-brackets/__testfixtures__/deeply-nested-sub.output.hbs
- transforms/angle-brackets/__testfixtures__/html-tags.output.hbs
- transforms/angle-brackets/__testfixtures__/input-helper.output.hbs
- transforms/angle-brackets/__testfixtures__/link-to-inline.input.hbs
- transforms/angle-brackets/__testfixtures__/link-to-inline.output.hbs
- transforms/angle-brackets/__testfixtures__/link-to-model-array.input.hbs
- transforms/angle-brackets/__testfixtures__/link-to-model-array.output.hbs
- transforms/angle-brackets/__testfixtures__/link-to-queryparam.input.hbs
- transforms/angle-brackets/__testfixtures__/link-to-queryparam.output.hbs
- transforms/angle-brackets/__testfixtures__/link-to.input.hbs
- transforms/angle-brackets/__testfixtures__/link-to.output.hbs
- transforms/angle-brackets/transforms/angle-brackets-syntax.js
fixes https://github.com/rajasegar/ember-angle-brackets-codemod/issues/55
> fix {{link-to}} dynamic route property

- transforms/angle-brackets/__testfixtures__/link-to-queryparam.input.hbs
- transforms/angle-brackets/__testfixtures__/link-to-queryparam.output.hbs
- transforms/angle-brackets/transforms/angle-brackets-syntax.js
fixes https://github.com/rajasegar/ember-angle-brackets-codemod/issues/58
> support `data-test-*` attributes in `{{link-to}}`

- transforms/angle-brackets/__testfixtures__/link-to-queryparam.input.hbs
- transforms/angle-brackets/__testfixtures__/link-to-queryparam.output.hbs
- transforms/angle-brackets/transforms/angle-brackets-syntax.js
Fixes https://github.com/rajasegar/ember-angle-brackets-codemod/issues/65
Checks whether the first param is the query-params or route and transforms accordingly
> Fix routeless LinkTo transformation

- transforms/angle-brackets/__testfixtures__/link-to-inline.input.hbs
- transforms/angle-brackets/__testfixtures__/link-to-inline.output.hbs
- transforms/angle-brackets/transforms/angle-brackets-syntax.js
Adds fix and failing test for https://github.com/rajasegar/ember-angle-brackets-codemod/issues/67
> Fix for inline link-to with dynamic text param

- transforms/angle-brackets/__testfixtures__/null-subexp.input.hbs
- transforms/angle-brackets/__testfixtures__/null-subexp.output.hbs
- transforms/angle-brackets/__testfixtures__/undefined-subexp.input.hbs
- transforms/angle-brackets/__testfixtures__/undefined-subexp.output.hbs
- transforms/angle-brackets/transforms/angle-brackets-syntax.js
> [BUGFIX] Fix undefined or null arg in sub expression

- README.md
> [DOCS] Add debugging workflow in README

- transforms/angle-brackets/__testfixtures__/link-to-queryparam.input.hbs
- transforms/angle-brackets/__testfixtures__/link-to-queryparam.output.hbs
- transforms/angle-brackets/transforms/angle-brackets-syntax.js
solves specific case in issue #77.  @GavinJoyce we can build off this if you like
> Inline link-to with query-param

- transforms/angle-brackets/__testfixtures__/link-to-model.input.hbs
- transforms/angle-brackets/__testfixtures__/link-to-model.output.hbs
- transforms/angle-brackets/transforms/angle-brackets-syntax.js
> fix number literal

- package-lock.json
- package.json
- transforms/angle-brackets/transforms/angle-brackets-syntax.js
This is to give some consistency to this codebase
> Pre-commit hook with Prettier

- README.md
Test PR to check where coveralls integration works properly.
Fixes #94
> [DOCS] Readme update

- package.json
This will help confusion here https://github.com/ember-cli/ember-cli-update-codemods-manifest/pull/16/files#diff-4b1eb3dc48c4e16d49db5b42298fe654R50.
> make node version explicit

- package-lock.json
- package.json
As discussed via Discord enforcing these checks on everyone can be problematic. e.g. certain git UI tools like https://git-fork.com/ don't work properly anymore, which makes committing and contributing to this project much harder than it needs to.
> Remove `husky` and `lint-staged` dev dependencies

- package.json
> package.json: Remove broken `main` field

- package.json
> Replace `ember-addon` keyword with `ember-codemod`

- transforms/angle-brackets/transform.js
This PR updates, sorts and documents the list of known common helpers, that should not be converted to angle brackets syntax.
> Update list of common helpers

- .travis.yml
- bin/cli.js
- package.json
It seems that currently we only run the test suite on CI, but not ESLint 😱
> CI: Run ESLint

- transforms/angle-brackets/test.js
failing test for https://github.com/rajasegar/ember-angle-brackets-codemod/issues/46
> Add whitespace control test

- transforms/angle-brackets/test.js
- transforms/angle-brackets/transform.js
> Fix inline link-to with subexpression caption crash

- transforms/angle-brackets/test.js
Closes https://github.com/ember-codemods/ember-angle-brackets-codemod/issues/112
> Add test case for splattributes

- transforms/angle-brackets/test.js
- transforms/angle-brackets/transform.js
> fix migrating away from arguments to attributes for non-builtins

- transforms/angle-brackets/test.js
- transforms/angle-brackets/transform.js
> `link-to` with conditional model

- transforms/angle-brackets/test.js
- transforms/angle-brackets/transform.js
> fix: handle link-to with computed target route

- RELEASE.md
- package.json
- yarn.lock
> Add automated release process.

- transforms/angle-brackets/transform.js
> Refactor nested functions to the outer scope

- transforms/angle-brackets/test.js
- transforms/angle-brackets/transform.js
Given
```hbs
{{shared/documents-modal/-email-client}}
```
Expect
```hbs
<Shared::DocumentsModal::-EmailClient />
```
> fix hyphen usage

- transforms/angle-brackets/test.js
this PR shows that #189 converts correctly
> codemod handles div and style tags in certain cases

- transforms/angle-brackets/test.js
- transforms/angle-brackets/transform.js
> Break out of transform if in attribute space

- README.md
- package.json
> [DOCS] Update debugging workflow in README

- README.md
This adds documentation for #241.
> Add note about includeValuelessDataTestAttributes

- README.md
- transforms/angle-brackets/index.js
- transforms/angle-brackets/transform.js
- transforms/angle-brackets/transform.test.js
Solves issue: https://github.com/ember-codemods/ember-angle-brackets-codemod/issues/436
This is my second-ever open-source PR - please provide feedback and suggestions on how to improve, I'd be happy to make the edits. ✏️
> [Feature]: Add ability to convert only specific component invocations with each run

- transforms/angle-brackets/transform.js
- transforms/angle-brackets/transform.test.js
> fix any number of models in link-to

- package.json
- yarn.lock
... apart from execa because that changed to ESM and requires a bigger change 😂
> update all dev-dependencies
