ember-codemods/ember-angle-brackets-codemod

README.md
transforms/angle-brackets/__testFixtures__/nested.input.hbs
transforms/angle-brackets/__testFixtures__/nested.output.hbs
transforms/angle-brackets/transforms/angle-brackets-syntax.js

Support the new nested component syntax
```hbs
{{ui/site-header user=this.user class=(if this.user.isAdmin "admin")}}
{{ui/button text="Click me"}}
{{#some-path/another-path/super-select selected=this.user.country as |s|}}
{{#each this.availableCountries as |country|}}
{{#s.option value=country}}{{country.name}}{{/s.option}}
{{/each}}
{{/some-path/another-path/super-select}}
```
```hbs
<Ui::SiteHeader @user={{this.user}} class={{if this.user.isAdmin "admin"}} />
<Ui::Button @text="Click me" />
<SomePath::AnotherPath::SuperSelect @selected={{this.user.country}} as |s|>
{{#each this.availableCountries as |country|}}
<s.option @value={{country}}>
{{country.name}}
</s.option>
{{/each}}
</SomePath::AnotherPath::SuperSelect>
```

Add support for transforming nested components

---

transforms/angle-brackets/__testFixtures__/t-helper.input.hbs
transforms/angle-brackets/__testFixtures__/t-helper.output.hbs
transforms/angle-brackets/transforms/angle-brackets-syntax.js

resolves #10 by ignoring the `t` helper provided by localization addons.
```hbs
{{! input }}
{{t "some.string" param=1}}
{{! output }}
<T
@param=1
/>
```
```hbs
{{! input }}
{{t "some.string" param=1}}
{{! output }}
{{t "some.string" param=1}}
```

add t helper to ignore mustache statements

---

transforms/angle-brackets/__testfixtures__/deeply-nested-sub.input.hbs
transforms/angle-brackets/__testfixtures__/deeply-nested-sub.output.hbs
transforms/angle-brackets/transforms/angle-brackets-syntax.js

towards https://github.com/rajasegar/ember-angle-brackets-codemod/issues/24
**input:**
```hbs
{{some-component person=(hash name="Sophie" age=1)}}
{{some-component
people=(array
(hash name="Alex" age=5 nested=(hash oldest=true))
(hash name="Ben" age=4)
(hash name="Sophie" age=1)
)
}}
```
**output:** (edit: updated to include double quotes)
```hbs
<SomeComponent @person={{hash name="Sophie" age=1}} />
<SomeComponent
@people={{array
(hash name="Alex" age=5 nested=(hash oldest=true))
(hash name="Ben" age=4)
(hash name="Sophie" age=1)
}}
/>
```

support nested subexpressions with named args

---

transforms/angle-brackets/__testfixtures__/data-attributes.input.hbs
transforms/angle-brackets/__testfixtures__/data-attributes.output.hbs
transforms/angle-brackets/transforms/angle-brackets-syntax.js

This fixes a case that I came across in my app
**input:**
```hbs
{{x-foo
data-foo
name="Sophie"
}}
```
**previous output:**
```hbs
<XFoo @name="Sophie" />
```
**current output:**
```hbs
<XFoo data-foo={{true}} @name="Sophie" />
```

improve support for data-* attributes

---

README.md
transforms/-preset.js
transforms/angle-brackets/__testfixtures__/custom-options.config.json
transforms/angle-brackets/__testfixtures__/custom-options.input.hbs
transforms/angle-brackets/__testfixtures__/custom-options.options.json
transforms/angle-brackets/__testfixtures__/custom-options.output.hbs
transforms/angle-brackets/transforms/angle-brackets-syntax.js

part of https://github.com/rajasegar/ember-angle-brackets-codemod/issues/12
This PR adds support for an optional `--config` argument:
`npx ember-angle-brackets-codemod angle-brackets app/templates --config ./config/anglebrackets-codemod-config.json`
This config file initially supports providing a list of helpers to help the codemod to disambiguate from components, eg:
```json
{
"helpers": ["ic-interface-icon", "date-formatter"]
}
```
While this isn't the perfect solution (it would be great if we could auto detect this information), it it good enough to unblock my attempts to use this codemod on my large ember app so I think it's worth landing.
Useful links:
* Here's where the options are set: https://github.com/rwjblue/codemod-cli/blob/3dd1e8e9496ea008cdcfbfa8f9191ee53460f372/src/bin-suppo …

Support optional config file containing list of helpers

---

transforms/angle-brackets/__testfixtures__/positional-params.input.hbs
transforms/angle-brackets/__testfixtures__/positional-params.output.hbs
transforms/angle-brackets/transforms/angle-brackets-syntax.js

part of https://github.com/rajasegar/ember-angle-brackets-codemod/issues/36
This PR skips components that have positional arguments and emit the following warning to the console:
`WARNING: {{some-component}} was not converted as it has positional parameters which can't be automatically converted. Source: /Users/gavinjoyce/dev/opensource/ember-angle-brackets-codemod/transforms/angle-brackets/__testfixtures__/positional-params.input.hbs`

skip and warn about components that have positional params

---

README.md
transforms/angle-brackets/__testfixtures__/custom-options.config.json
transforms/angle-brackets/__testfixtures__/custom-options.input.hbs
transforms/angle-brackets/__testfixtures__/custom-options.output.hbs
transforms/angle-brackets/transforms/angle-brackets-syntax.js

closes https://github.com/rajasegar/ember-angle-brackets-codemod/issues/43

add `skipBuiltInComponents` config option

---

.gitignore
package-lock.json
package.json
transforms/angle-brackets/__testfixtures__/entities.input.hbs
transforms/angle-brackets/__testfixtures__/entities.output.hbs
transforms/angle-brackets/transforms/angle-brackets-syntax.js

Fixes #48 
Updates `@glimmer/syntax` to 0.41.0 and turns on `codemod` mode. Also grabs the failing entities test from #49 
/cc @rwjblue @GavinJoyce

Upgrade @glimmer/syntax and turn on `codemod` mode

---

transforms/angle-brackets/__testfixtures__/deeply-nested-sub.input.hbs
transforms/angle-brackets/__testfixtures__/deeply-nested-sub.output.hbs
transforms/angle-brackets/transforms/angle-brackets-syntax.js

I noticed that `disabled=(eq foo "bar")` was being transformed to ``disabled=(eq foo bar)`. This PR fixes that

fix expression with string literal param

---

transforms/angle-brackets/__testfixtures__/nested.input.hbs
transforms/angle-brackets/__testfixtures__/nested.output.hbs
transforms/angle-brackets/transforms/angle-brackets-syntax.js

This PR converts `{{x-foo/x-bar}}` into `<XFoo::XBar />`

Convert nested components which have no arguments

---

transforms/angle-brackets/__testfixtures__/sample.input.hbs
transforms/angle-brackets/__testfixtures__/sample.output.hbs
transforms/angle-brackets/transforms/angle-brackets-syntax.js

this fixes component params that have the values of `null` or `undefined`

handle null and undefined` arguments

---

transforms/angle-brackets/__testfixtures__/positional-params.input.hbs
transforms/angle-brackets/__testfixtures__/positional-params.output.hbs
transforms/angle-brackets/transforms/angle-brackets-syntax.js

this will skip components which have positional params like:
```hbs
{{#some-component foo}}
hi
{{/some-component}}
```

skip components with positional params which are paths

---

transforms/angle-brackets/transforms/angle-brackets-syntax.js

Don't emit warnings for `with` keyword

add `with` as built-in keyword

---

transforms/angle-brackets/__testfixtures__/sample2.input.hbs
transforms/angle-brackets/__testfixtures__/sample2.output.hbs
transforms/angle-brackets/transforms/angle-brackets-syntax.js

While `card.foo-bar` is ambiguous and could be a property, I think it's overwhelmingly likely to be a component.
This converts the following:
```hbs
{{#my-card as |card|}}
{{card.foo-bar}}
{{card.foo}}
{{/my-card}}
```
to:
```hbs
<MyCard as |card|>
<card.foo-bar />
{{card.foo}}
</MyCard>
```

convert yielded components which contain a `-`

---

transforms/angle-brackets/__testfixtures__/link-to-model.input.hbs
transforms/angle-brackets/__testfixtures__/link-to-model.output.hbs
transforms/angle-brackets/transforms/angle-brackets-syntax.js

This PR fixes an issue where having a `link-to` model as a string literal isn't converted correctly.
```hbs
{{#link-to "post" "string-id"}}Read {{post.title}}...{{/link-to}}
```
```hbs
<LinkTo @route="post" @model={{string-id}}>
Read
{{post.title}}
...
</LinkTo>
```
```hbs
<LinkTo @route="post" @model="string-id">
Read
{{post.title}}
...
</LinkTo>
```

Fix issue where `link-to` model as string literal isn't converted correctly

---

LICENSE
README.md
package.json
transforms/-preset.js
transforms/angle-brackets/transforms/angle-brackets-syntax.js

Since we have transferred the repo to the new org
ember-codemods, removing all the author references
and replacing with ember-codemods
Fixes #91

[CHORE] Remove rajasegar:author references

---

.eslintrc.js

Apparently we currently only support running tests in `test.js` files due to how `codemod-cli` is implemented 🤔

ESLint: Fix test path pattern

---

bin/cli.js

Without this change the codemod would only run on JS files 😱 
This configures the codemod to run on Handlebars files instead of JS files.

bin/cli: Set correct file extension

---

transforms/angle-brackets/__snapshots__/test.js.snap
transforms/angle-brackets/test.js

The previous fixture wasn't actually checking the implemented behavior of completely ignoring templates that include a tilde character.

Adjust `tilde` test fixture

---

package-lock.json
package.json
transforms/angle-brackets/test.js
transforms/angle-brackets/transform.js

refactors to ease modification and to support ember template recast a bit better

Use `ember-template-recast` to preserve existing template formatting as much as possible

---

transforms/angle-brackets/test.js

This PR adds a regression test for https://github.com/ember-template-lint/ember-template-recast/issues/126. The fix for this landed here in https://github.com/ember-codemods/ember-angle-brackets-codemod/pull/161.

Add test case for nested else if

---

transforms/angle-brackets/test.js
transforms/angle-brackets/transform.js

This was causing issues in our app in a few rare cases where this feature was unfortunately used :-/

Skip block component conversion if the component has an `inverse` block

---

transforms/angle-brackets/test.js
transforms/angle-brackets/transform.js

Enabled by https://github.com/glimmerjs/glimmer-vm/pull/983
Resolves #46
/cc @GavinJoyce

Add support for templates containing `~` (whitespace control)

---

transforms/angle-brackets/telemetry/mock-invokables.js
transforms/angle-brackets/transform.js
transforms/angle-brackets/transform.test.js

previously, telemetry (helpers + components arrays) would only include the path after the `/helpers/` section of the string. for most apps, this meant that 
```
app/helpers/my/cool/helper
```
would be stored in the helpers array as 
```
"my/cool/helper"
```
for apps using engines & wallstreet syntax, the `MustacheStatement` transform for namespaced components would be looking for the helper/component using the namespaced key, which would never exist.
This PR changes the transform to strip out the namespace (anything before `$`), and replace any `::` with `/`'s to ensure that the transform uses the same syntax as the telemetry data

fix wallstreet integration with telemetry data

---

transforms/angle-brackets/transform.js
transforms/angle-brackets/transform.test.js

The original logic would consider any parameter a data attribute if the `original` had the substring `data-` .  This fix further reduces the ambiguity of the  parameter by enforcing that it also can't be a `StringLiteral` and that it must be a `PathExpression`
This fixes #212

Fix false negatives for `link-to` with `data-` prefixed route name

---

README.md
transforms/angle-brackets/transform.js
transforms/angle-brackets/transform.test.js

Fixes #206 
This fix will allow users to provide an array of custom regex for skipping prefixing of `@`.
This would be done by passing in the extra property `skipAttributesThatMatchRegex` and the value would be an array of regex strings.

Add support to skip prefixing `@` for user provided attributes

---

README.md
transforms/angle-brackets/transform.js
transforms/angle-brackets/transform.test.js

Accept `skipAttributesThatMatchRegex ` option values as an array of regex strings

---

transforms/angle-brackets/index.js
transforms/angle-brackets/transform.test.js

`skipAttributesThatMatchRegex` wasn't getting included in the transform config

Add skipAttributesThatMatchRegex to config

---

transforms/angle-brackets/index.js
transforms/angle-brackets/transform.js
transforms/angle-brackets/transform.test.js

The current codemod skips on transforming nodes with valueless attributes. This prevents a full migration for those who use libraries like [ember-test-selectors](https://github.com/simplabs/ember-test-selectors).
This PR adds the config `includeValuelessDataAttributes` so the codemod includes data attributes that are valueless.
https://github.com/ember-codemods/ember-angle-brackets-codemod/issues/237

Add config to enable transform on valueless attrs

---

README.md

I haven't tried this yet, but in reviewing #287 it occurred to me that I'm pretty sure you'd want to configure this to at least skip helpers when running w/o telemetry.

add a note on skipping helpers when running w/o telemetry
